name: CaptureShare CI

on:
  push:
  pull_request:


jobs:
  tsc:
    name: CaptureShare CI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Node v14.2.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - name: Build CaptureShare
      run: (cd client && yarn build && cd ../server && yarn build && cd ../app && yarn build)
